# Week 1: Extracting relevant data/subgraph from CARD and PrimeKG

In [3]:
import pandas as pd
import numpy as np

## Obtaining dataframe of Resistance_genes, Pathogens, Resistance mechanisms, Antibiotics from [CARD](https://card.mcmaster.ca/prevalence)

In [ ]:
# Original file in .txt format. 
# Converted to .csv using online converter (https://mconverter.eu/convert/txt/csv/). 
# Cleaned in Excel to place mechanisms and drug classes in the right columns, because some were switched. 

data_amr = pd.read_csv('card-prevalence/card_prevalence.csv')

In [5]:
data_amr.tail(3)

,ARO_Accession,Name,Model_ID,Model_Type,Pathogen,NCBI_Plasmid,NCBI_WGS,NCBI_Chromosome,NCBI_Genomic_Island,Criteria,...,Unnamed: 17,Unnamed: 18,Unnamed: 19,Unnamed: 20,Unnamed: 21,Unnamed: 22,Unnamed: 23,Unnamed: 24,Unnamed: 25,Unnamed: 26
20038,ARO:3007473,Mycobacterium avium gyrA with mutation conferr...,5956,protein variant model,Corynebacterium ulcerans,0.0,4.55,0.00,0.0,perfect_strict,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20039,ARO:3007473,Mycobacterium avium gyrA with mutation conferr...,5956,protein variant model,Corynebacterium amycolatum,0.0,3.70,14.29,0.0,perfect_strict,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20040,ARO:3007473,Mycobacterium avium gyrA with mutation conferr...,5956,protein variant model,Corynebacterium jeikeium,0.0,0.00,40.00,0.0,perfect_strict,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
unnamed_cols = [data_amr.columns[a] for a in range(len(data_amr.columns)) if 'Unnamed' in data_amr.columns[a]] #Gathering antibiotic columns since they are unnamed due to the original set up and the converter

In [7]:
#temp_data = data_amr.head(5)
#temp_data[unnamed_cols].apply(lambda x: ','.join(x.dropna()),axis = 1)

In [ ]:
#data_amr.head()
data_amr['Drug_Class'] = data_amr[unnamed_cols].apply(lambda x: ','.join(x.dropna()),axis = 1) #Creating a column with Antibiotics by merging all columns, ignoring NaNs, seperated by ',
data_amr.drop(unnamed_cols, axis = 1, inplace = True)

In [9]:
data_amr.tail(3)

,ARO_Accession,Name,Model_ID,Model_Type,Pathogen,NCBI_Plasmid,NCBI_WGS,NCBI_Chromosome,NCBI_Genomic_Island,Criteria,ARO_Categories,Drug_Class
20038,ARO:3007473,Mycobacterium avium gyrA with mutation conferr...,5956,protein variant model,Corynebacterium ulcerans,0.0,4.55,0.00,0.0,perfect_strict,antibiotic target alteration,"fluoroquinolone antibiotic, nybomycin-like an..."
20039,ARO:3007473,Mycobacterium avium gyrA with mutation conferr...,5956,protein variant model,Corynebacterium amycolatum,0.0,3.70,14.29,0.0,perfect_strict,antibiotic target alteration,"fluoroquinolone antibiotic, nybomycin-like an..."
20040,ARO:3007473,Mycobacterium avium gyrA with mutation conferr...,5956,protein variant model,Corynebacterium jeikeium,0.0,0.00,40.00,0.0,perfect_strict,antibiotic target alteration,"fluoroquinolone antibiotic, nybomycin-like an..."

In [ ]:
data_amr.rename(columns = {'ARO_Categories':'Resistance_Mechanism', 'Name':'Resistant_Gene'}, inplace = True)
data_amr.drop(['Model_ID', 'Model_Type', 'NCBI_Plasmid', 'NCBI_WGS', 'NCBI_Chromosome', 'NCBI_Genomic_Island', 'Criteria'], axis = 1, inplace = True) #Dropping (what I believe are) irrelevant columns

In [11]:
data_amr.tail(6)

,ARO_Accession,Resistant_Gene,Pathogen,Resistance_Mechanism,Drug_Class
20035,ARO:3007463,IMP-93,Pseudomonas aeruginosa,antibiotic inactivation,"carbapenem, cephalosporin, cephamycin, penam,..."
20036,ARO:3007473,Mycobacterium avium gyrA with mutation conferr...,Corynebacterium diphtheriae,antibiotic target alteration,"fluoroquinolone antibiotic, nybomycin-like an..."
20037,ARO:3007473,Mycobacterium avium gyrA with mutation conferr...,Corynebacterium urealyticum,antibiotic target alteration,"fluoroquinolone antibiotic, nybomycin-like an..."
20038,ARO:3007473,Mycobacterium avium gyrA with mutation conferr...,Corynebacterium ulcerans,antibiotic target alteration,"fluoroquinolone antibiotic, nybomycin-like an..."
20039,ARO:3007473,Mycobacterium avium gyrA with mutation conferr...,Corynebacterium amycolatum,antibiotic target alteration,"fluoroquinolone antibiotic, nybomycin-like an..."
20040,ARO:3007473,Mycobacterium avium gyrA with mutation conferr...,Corynebacterium jeikeium,antibiotic target alteration,"fluoroquinolone antibiotic, nybomycin-like an..."

In [12]:
#Pathogens of interest: 
#Research_plan: Klebsiella pneumoniae, Streptococcus pneumoniae, Escherichia coli, Acinetobacter baumannii, Mycobacterium tuberculosis 
#Additional from reading notes: Enterococcus faecalis, Staphylococcus aureus, Pseudomonas aeruginosa

In [13]:
pathogens_of_interest = ['Klebsiella pneumoniae', 'Streptococcus pneumoniae', 'Escherichia coli', 'Acinetobacter baumannii', 'Mycobacterium tuberculosis', 'Enterococcus faecalis', 'Staphylococcus aureus', 'Pseudomonas aeruginosa']

In [14]:
data_amr_poi = data_amr[data_amr['Pathogen'].isin(pathogens_of_interest)]
len(data_amr_poi)

4356

Final dataset from CARD for pathogens related to T2DM below:

In [15]:
data_amr_poi.head(5)

,ARO_Accession,Resistant_Gene,Pathogen,Resistance_Mechanism,Drug_Class
2,ARO:3003390,Escherichia coli ompF with mutation conferring...,Escherichia coli,reduced permeability to antibiotic,"carbapenem, cephalosporin, cephamycin, monobac..."
3,ARO:3001109,SHV-52,Klebsiella pneumoniae,antibiotic inactivation,"carbapenem, cephalosporin, penam"
4,ARO:3001109,SHV-52,Klebsiella pneumoniae,antibiotic inactivation,"carbapenem, cephalosporin, penam"
7,ARO:3002867,dfrF,Enterococcus faecalis,antibiotic target replacement,diaminopyrimidine antibiotic
30,ARO:3002867,dfrF,Staphylococcus aureus,antibiotic target replacement,diaminopyrimidine antibiotic

## Data from [PrimeKG on Harvard Dataverse](https://dataverse.harvard.edu/dataset.xhtml?persistentId=doi:10.7910/DVN/IXA7BM)

In [ ]:
disease_features = pd.read_csv('dataverse_files/disease_features.csv')
primekg_nodes = pd.read_csv('dataverse_files/nodes.csv')
primekg_edges = pd.read_csv('dataverse_files/edges.csv')
primekg = pd.read_csv('dataverse_files/kg.csv')

/tmp/ipykernel_2108715/867168139.py:4: DtypeWarning: Columns (3,8) have mixed types. Specify dtype option on import or set low_memory=False.
  primekg = pd.read_csv('dataverse_files/kg.csv')

In [ ]:
#primekg_nodes[primekg_nodes['node_type'] == 'effect/phenotype']
#primekg_edges.head(5)

In [ ]:
primekg_nodes[primekg_nodes['node_name'] == 'type 2 diabetes mellitus']

       node_index node_id node_type                 node_name node_source
28208       28208    5148   disease  type 2 diabetes mellitus       MONDO

In [ ]:
len(primekg)

8100498

In [ ]:
v1_t2dm = primekg[(primekg['x_name'] == 'type 2 diabetes mellitus') | (primekg['y_name'] == 'type 2 diabetes mellitus')] #Version 1 of T2DM  subgraph, relations where T2DM is either a source or recepient.

v1_t2dm = v1_t2dm[~(v1_t2dm['x_type'] == 'exposure') & ~(v1_t2dm['y_type'] == 'exposure')] #Ignoring 'exposure' nodes.
v1_t2dm.head(5)

,relation,display_relation,x_index,x_id,x_type,x_name,x_source,y_index,y_id,y_type,y_name,y_source
368612,indication,indication,14813,DB00197,drug,Troglitazone,DrugBank,28208,5148,disease,type 2 diabetes mellitus,MONDO
368614,contraindication,contraindication,20330,DB11396,drug,Dichlorophen,DrugBank,28208,5148,disease,type 2 diabetes mellitus,MONDO
368616,indication,indication,14166,DB00414,drug,Acetohexamide,DrugBank,28208,5148,disease,type 2 diabetes mellitus,MONDO
368618,indication,indication,14603,DB00672,drug,Chlorpropamide,DrugBank,28208,5148,disease,type 2 diabetes mellitus,MONDO
368620,indication,indication,15770,DB00222,drug,Glimepiride,DrugBank,28208,5148,disease,type 2 diabetes mellitus,MONDO

In [ ]:
#According to the PrimeKG schema, there may be drug-phenotype, phenotype-gene, gene-pathway and gene-BP/MF/CC relations that lead to indirect connections to T2DM.

relevant_drugs1 = v1_t2dm[v1_t2dm['x_type'] == 'drug']['x_index'].values.tolist()
relevant_drugs2 = v1_t2dm[v1_t2dm['y_type'] == 'drug']['y_index'].values.tolist()
relevant_phenotypes1 = v1_t2dm[v1_t2dm['x_type'] == 'effect/phenotype']['x_index'].values.tolist()
relevant_phenotypes2 = v1_t2dm[v1_t2dm['y_type'] == 'effect/phenotype']['y_index'].values.tolist()
relevant_genes1 = v1_t2dm[v1_t2dm['x_type'] == 'gene/protein']['x_index'].values.tolist()
relevant_genes2 = v1_t2dm[v1_t2dm['y_type'] == 'gene/protein']['y_index'].values.tolist()

In [ ]:
relevant_drugs = list(set(relevant_drugs1 + relevant_drugs2))
relevant_phenotypes = list(set(relevant_phenotypes1 + relevant_phenotypes2))
relevant_genes = list(set(relevant_genes1 + relevant_genes2))

In [ ]:
# drug-phenotype

additional_relevant_drug_phenotype_edges1 = primekg[(primekg['x_index'].isin(relevant_drugs)) & (primekg['y_index'].isin(relevant_phenotypes))]
additional_relevant_drug_phenotype_edges2 = primekg[(primekg['x_index'].isin(relevant_phenotypes)) & (primekg['y_index'].isin(relevant_drugs))]

In [ ]:
additional_relevant_drug_phenotype_edges2 #Seems like there is no relevant edge between drugs and phenotype missed

Empty DataFrame
Columns: [relation, display_relation, x_index, x_id, x_type, x_name, x_source, y_index, y_id, y_type, y_name, y_source]
Index: []

In [ ]:
#phenotype-gene
additional_relevant_phenotype_gene_edges1 = primekg[(primekg['x_index'].isin(relevant_phenotypes)) & (primekg['y_index'].isin(relevant_genes))] 
additional_relevant_phenotype_gene_edges2 = primekg[(primekg['x_index'].isin(relevant_genes)) & (primekg['y_index'].isin(relevant_phenotypes))]

In [ ]:
#gene-pathway/BP/MF/CC
additional_relevant_genes_pathway_BP_MF_CC_edges1 = primekg[(primekg['x_index'].isin(relevant_genes)) & (primekg['y_type'].isin(['pathway', 'biological_process', 'molecular_function', 'cellular_component']))]
additional_relevant_genes_pathway_BP_MF_CC_edges2 = primekg[(primekg['x_type'].isin(['pathway', 'biological_process', 'molecular_function', 'cellular_component'])) & (primekg['y_index'].isin(relevant_genes))]

In [ ]:
v2_t2dm = pd.concat([v1_t2dm, additional_relevant_drug_phenotype_edges1, additional_relevant_drug_phenotype_edges2, additional_relevant_phenotype_gene_edges1, additional_relevant_phenotype_gene_edges2, additional_relevant_genes_pathway_BP_MF_CC_edges1, additional_relevant_genes_pathway_BP_MF_CC_edges2])
len(v2_t2dm)

15128

Final T2DM dataset/subgraph of PrimeKG including indirect drugs-phenotype, phenotype-genes, and gene-pathway/biological process/molecular function/cellular compound relations.

In [ ]:
v2_t2dm.head(5)

,relation,display_relation,x_index,x_id,x_type,x_name,x_source,y_index,y_id,y_type,y_name,y_source
368612,indication,indication,14813,DB00197,drug,Troglitazone,DrugBank,28208,5148,disease,type 2 diabetes mellitus,MONDO
368614,contraindication,contraindication,20330,DB11396,drug,Dichlorophen,DrugBank,28208,5148,disease,type 2 diabetes mellitus,MONDO
368616,indication,indication,14166,DB00414,drug,Acetohexamide,DrugBank,28208,5148,disease,type 2 diabetes mellitus,MONDO
368618,indication,indication,14603,DB00672,drug,Chlorpropamide,DrugBank,28208,5148,disease,type 2 diabetes mellitus,MONDO
368620,indication,indication,15770,DB00222,drug,Glimepiride,DrugBank,28208,5148,disease,type 2 diabetes mellitus,MONDO